name: Deploy to Oracle Cloud VM

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - dev
          - prod
      image_tag:
        description: 'Custom image tag (defaults to commit SHA if not specified)'
        required: false
        type: string
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/sad-api:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/sad-api:${{ inputs.image_tag || github.sha }}

      - name: Deploy to Oracle Cloud VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ORACLE_VM_HOST }}
          username: ${{ secrets.ORACLE_VM_USERNAME }}
          key: ${{ secrets.ORACLE_VM_SSH_KEY }}
          script: |
            # Pull the latest image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sad-api:${{ inputs.image_tag || github.sha }}
            
            # Stop and remove existing container if it exists
            docker stop sad_container || true
            docker rm sad_container || true
            
            # Install OCI CLI if not already installed
            if ! command -v /home/ubuntu/bin/oci &> /dev/null; then
              echo "Installing OCI CLI..."
              # Install required packages
              sudo apt-get update
              sudo apt-get install -y python3-pip
              # Install OCI CLI
              pip3 install oci-cli
            fi
            
            # Configure OCI CLI if not already configured
            mkdir -p ~/.oci
            
            # Check and create config file if it doesn't exist
            if [ ! -f ~/.oci/config ]; then
              echo "Creating OCI config file..."
              echo "${{ secrets.ORACLE_CLI_CONFIG }}" > ~/.oci/config
            else
              echo "OCI config file already exists, skipping creation"
            fi
            
            # Check and create API key file if it doesn't exist
            if [ ! -f ~/.oci/oci_api_key.pem ]; then
              echo "Creating OCI API key file..."
              echo "${{ secrets.ORACLE_CLI_KEY }}" > ~/.oci/oci_api_key.pem
              chmod 600 ~/.oci/oci_api_key.pem
            else
              echo "OCI API key file already exists, skipping creation"
            fi
            
            # Test OCI CLI configuration
            # /home/ubuntu/bin/oci iam user get --user-id ${{ secrets.ORACLE_USER_OCID }}
            if ! /home/ubuntu/bin/oci iam user get --user-id ${{ secrets.ORACLE_USER_OCID }} &> /dev/null; then
              echo "Error: Failed to authenticate with OCI CLI"
              exit 1
            fi
            
            # Fetch secrets from Oracle Cloud Vault
            OPENAI_API_KEY=$(/home/ubuntu/bin/oci secrets secret-bundle get-secret-bundle-by-name \
              --vault-id ${{ secrets.ORACLE_VAULT_OCID }} \
              --secret-name OPENAI_API_KEY \
              --query "data.\"secret-bundle-content\".content" \
              --raw-output | base64 --decode)
            
            # Verify the API key was retrieved
            if [ -z "$OPENAI_API_KEY" ]; then
              echo "Error: Failed to retrieve OPENAI_API_KEY from vault"
              exit 1
            fi
            
            # Run the new container with secrets
            docker run -d \
              --name sad_container \
              -p 80:8080 \
              --restart unless-stopped \
              -e OPENAI_API_KEY="$OPENAI_API_KEY" \
              ${{ secrets.DOCKERHUB_USERNAME }}/sad-api:${{ inputs.image_tag || github.sha }}
            
            # Clean up OCI config
            # rm -rf ~/.oci