name: Deploy to Oracle Cloud VM

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sad-api:${{ github.sha }}

      - name: Deploy to Oracle Cloud VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ORACLE_VM_HOST }}
          username: ${{ secrets.ORACLE_VM_USERNAME }}
          key: ${{ secrets.ORACLE_VM_SSH_KEY }}
          script: |
            # Pull the latest image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sad-api:${{ github.sha }}
            
            # Stop and remove existing container if it exists
            docker stop sad_containter || true
            docker rm sad_containter || true
            
            # Run the new container
            docker run -d \
              --name sad_containter \
              -p 80:8080 \
              --restart unless-stopped \
              ${{ secrets.DOCKERHUB_USERNAME }}/sad-api:${{ github.sha }} 
